config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'toppage#index'

  resources :user_menu, only: [:show, :create]

  resources :products, except: :show

  resources :products, only: :show do
    post "/card", to: "card#buy"
  end

  get "/products/show2/:id", to: "products#show2"

  resources :users, only: [:index, :show, :new, :edit, :update] do
    resources :addresses, only: [:new, :create, :update]
  end
  
  resources :card, only: [:new, :index, :create, :destroy]

  resources :users do
    get "/products", to: "products#user_index"
  end

  resources :exhibition, only: [:index] 
end

app/models/address.rb
class Address < ApplicationRecord
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :zip, presence: true, length: { is: 7 }
  validates :area_id, presence: true
  validates :user_id, presence: true
  validates :city, presence: true
  validates :number, presence: true

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :area

end

app/models/area.rb
class Area < ActiveHash::Base

  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/card.rb
class Card < ApplicationRecord
  validates :user_id, presence: true, uniqueness: true
  validates :customer_id, presence: true
  validates :card_id, presence: true

  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image,  presence: true

  belongs_to :product

end

app/models/postage.rb
class Postage < ActiveHash::Base
  self.data = [
    {id: 1, text: '送料込み(出品者負担)'},
    {id: 2, text: '着払い(購入者負担)'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  

  has_many :pictures, dependent: :destroy
  belongs_to :category
  belongs_to :user
  
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :name,:text,  presence: true
  validates :price, numericality:{greater_than: 300, less_than: 10000000}, presence: true
  validates :category_id, :size_id, :status_id, :postage_id, :area_id, :shipping_date_id, :user_id, presence: true

  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :status
  belongs_to_active_hash :area
  belongs_to_active_hash :postage
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :status
end

app/models/shipping_date.rb
class ShippingDate < ActiveHash::Base
  self.data = [
    {id: 1, text: '1~2日で発送'},
    {id: 2, text: '2~3日で発送'},
    {id: 3, text: '4~7日で発送'}
]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, text: 'Sサイズ'},
    {id: 2, text: 'Mサイズ'},
    {id: 3, text: 'Lサイズ'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, text: '新品、未使用'},
    {id: 2, text: '未使用に近い'},
    {id: 3, text: '目立った傷や汚れなし'},
    {id: 4, text: 'やや傷や汚れあり'},
    {id: 5, text: '傷や汚れあり'},
    {id: 6, text: '全体的に状態が悪い'}
]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 7 }, confirmation: true, unless: :without_validate
  attr_accessor :without_validate
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :dob, presence: true

  has_one :address
  has_many :products
  has_one :card
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/exhibition_helper.rb
module ExhibitionHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/helpers/user_menu_helper.rb
module UserMenuHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample77b
    %script{src: "https://js.pay.jp/", type: "text/javascript"}

    = include_gon

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'templates/exhibition-btn'
    = yield

app/views/purchase/complete.html.haml
.simple-header
  = render partial: 'logo-header'    
.body
  .content
    .content__title
      購入が完了しました！
    .content__message
      購入完了しました。出品者の発送通知をお待ちください。
    .content__home
      .content__home__btn
        =link_to "/", class: "content__home__btn__link" do
          ホームへ
.simple-footer
  = render partial: 'logo-footer'

app/views/purchase/confirmation.html.haml
.simple-header
  = render partial: 'logo-header'
.contents
  .content
    .contet__title
      .content__title__name
        購入内容の確認
    .content__product
      .content__product__items
        .content__product__items__img
          = image_tag "logo.png", size: "64x64"
        .content__product__items__name
          必ず幸せになれる不思議な壺
          %p¥128,000（税込）送料込み
    .content__price
      .content__price__show
        支払い金額
      .content__price__shipping-fee
        ¥128,000
    .content__credit    
      .content__credit__title
        支払い方法
        =link_to "#/#", class:"content__credit__title__edit" do
          変更する
      .content__credit__box  
        .content__credit__box__name
          クレジットカード
        .content__credit__box__number
          1248127412
        .content__credit__box__day
          1/2
        .content__credit__box__img
          = image_tag "Mastercard-logo.svg.png", size: "16x16"  
    .content__address
      .content__address__title
        配送先
        =link_to "#/#", class:"content__address__title__edit" do
          変更する  
      .content__address__box
        .content__address__box__zip
        〒819-1335
        .content__address__box__number
        福岡県糸島市志摩芥屋1-1
        .content__address__box__name
        田中知樹
    .content__buy
      .content__buy__btn
        =link_to "user_menu/new/create", class:"content__buy__btn__submit" do
          購入する
.simple-footer
  = render partial: 'logo-footer'

app/views/templates/_download-footer.html.haml
.down-footer
  .down-footer__download
    = image_tag "footer/download/footer-pict.jpg", class:"down-footer__download__image"

    .down-footer__download__content
      .down-footer__download__content__title
        誰でもかんたん、人生を変えるフリマアプリ
      %p.down-footer__download__content__subtitle
        今すぐ無料ダウンロード！
      .down-footer__download__content__icons
        = image_tag "main/visual/apple_logo.svg", size:"180x60", class:"down-footer__download__content__icons__apple"
        = image_tag "main/visual/google-play-badge.png", size:"230x90", class:"down-footer__download__content__icons__goo"

  .down-footer__reference
    .down-footer__reference__contents
      .down-footer__reference__contents__about
        .down-footer__reference__contents__about__title
          FURIMAについて
        %ul
          %li
            = link_to "会社概要（運営会社）", '#', class: 'down-footer__reference__contents__about--link'
          %li
            = link_to "プライバシーポリシー", '#', class: 'down-footer__reference__contents__about--link'
          %li
            = link_to "FURIMA利用規約", '#', class: 'down-footer__reference__contents__about--link'
          %li
            = link_to "ポイントに関する特約", '#', class: 'down-footer__reference__contents__about--link'

      .down-footer__reference__contents__lists
        .down-footer__reference__contents__lists__title
          FURIMAを見る
        %ul
          %li
            = link_to "カテゴリ一覧", '#', class: 'down-footer__reference__contents__lists--link'
          %li
            = link_to "ブランド一覧", '#', class: 'down-footer__reference__contents__lists--link'
            
      .down-footer__reference__contents__help
        .down-footer__reference__contents__help__title
          ヘルプ＆ガイド
        %ul
          %li
            = link_to "FURIMAガイド", '#', class: 'down-footer__reference__contents__help--link'      
          %li
            = link_to "FURIMAロゴ利用ガイドライン", '#', class: 'down-footer__reference__contents__help--link' 
          %li
            = link_to "お知らせ", '#', class: 'down-footer__reference__contents__help--link'    

    .down-footer__reference__logo
      .down-footer__reference__logo--wrap
        .down-footer__reference__logo__icon
          = image_tag "footer/reference/logo-white.png", size:"160x50", class:"down-footer__reference__logo__icon__image"
        @ FURIMA

app/views/templates/_exhibition-btn.html.haml
-if user_signed_in?
  = link_to  new_product_path, class:'exhibition-btn' do
    出品する
    .exhibition-btn__icon    
      = image_tag "exhibition-btn/camera_icon.png",size:'80x80'

app/views/templates/_list.html.haml
= link_to user_menu_path(id: "#{code}", name: "#{name}"), class:"user-menu__main__list__mypage--link" do
  = "#{name}"       
  .user-menu__main__list__mypage__arrow
    ＞

app/views/templates/_logo-footer.html.haml
.simple-footer__logo
  =image_tag "footer/logo-white.png", size:"180x65", class:"simple-footer__logo__img"
  .simple-footer__text
    ©Furima, inc

app/views/templates/_logo-header.html.haml
= link_to root_path, class: "simple-header__Btn" do
  = image_tag "header/logo.png", size: "185x49", class:"simple-header__btn__img"

app/views/templates/_product-overview.html.haml
.product-overview
  .product-overview__image
    = link_to product_path(product.id, category_id: product.category_id) do
      = image_tag product.pictures[0].image.url, size:'190x150'
  .product-overview__name
    -# 商品サンプル
    = product.name
  .product-overview__info
    .product-overview__info__price
      -# ¥3,000
      = number_to_currency(product.price)
      .product-overview__info__price__tax
        (税込)
    .product-overview__info__favorites
      = icon('fas','star')
      0
      .product-overview__info__status
        - if product.purchase
          売り切れ
        - else
          出品中
          
              

app/views/templates/_search-header.html.haml
.search-header
  .search-header__upper
    .search-header__upper__logo
      = link_to root_path do
        = image_tag "header/logo.png", size:"140x40", class:"search-header__upper__logo__image"
    .search-header__upper__form 
      = form_with url:'#', class:"search-header__upper__form__field"   do |form|
        .search-header__upper__form__field__input
          = form.text_field :keyword,placeholder:" キーワードから探す", class: 'search-header__upper__form__field__input__content'
        .search-header__upper__form__field__search
          %label
            .search-header__upper__form__field__search__box
              = image_tag "header/icon-search.png", size:"20x20",class:"search-header__upper__form__field__search__box__icon"
            = form.submit '%', class:"search-header__upper__form__field__search__btn"

  .search-header__lower
    .search-header__lower__products
      .search-header__lower__products__categories
        .search-header__lower__products__categories__title
          カテゴリー
        .search-header__lower__products__categories__lists
          .search-header__lower__products__categories__lists--lv1
            - categories.each do |category1|
              .search-header__lower__products__categories__lists--lv1__content
                = link_to category1.name, products_path(id: category1.id,all_view:'false'), class:"search-header__lower__products__categories__lists--lv1__content--link"
                .search-header__lower__products__categories__lists--lv1__content--lv2
                  - category1.children.each do |category2|
                    .search-header__lower__products__categories__lists--lv1__content--lv2__content
                      = link_to category2.name, products_path(id: category2.id,all_view:'false'), class:"search-header__lower__products__categories__lists--lv1__content--lv2__content--link"
                      .search-header__lower__products__categories__lists--lv1__content--lv2__content--lv3
                        - category2.children.each do |category3|
                          .search-header__lower__products__categories__lists--lv1__content--lv2__content--lv3__content
                            = link_to category3.name, products_path(id: category3.id,all_view:'false'), class:"search-header__lower__products__categories__lists--lv1__content--lv2__content--lv3__content--link"
               
      .search-header__lower__products__brand
        ブランド
    .search-header__lower__user
      - if user_signed_in?
        .search-header__lower__user__registration
          = link_to 'マイページ', user_menu_path(101), name:'マイページ'
      - else
        .search-header__lower__user__login
          = link_to 'ログイン', new_user_session_path
        .search-header__lower__user__registration
          = link_to '新規登録', new_user_registration_path

app/views/templates/_user-products.html.haml
.user-products__items
  .user-products__items__title
    .user-products__items__title__name
      %h1 商品名：
      = product.name
    .user-products__items__title__price
      %h2 (価格：
      %span
        = product.price
      %h2  円)
  .user-products__items__box
    - if user_signed_in? && current_user.id == product.user_id 
      - unless product.purchase 
        .user-products__items__box__edit
          =link_to "編集", edit_product_path(product.id), class: "user-products__items__box__edit__btn"
        .user-products__items__box__destroy
          =link_to "削除", product_path(product.id), method: :delete, class: "user-products__items__box__destroy__btn"
      - else 
        .user-products__items__box__sold
          この商品は他のユーザーが購入済みです

app/views/templates/_usermenu-sidebar.html.haml
.user-menu__main__list
  %ul.user-menu__main__list__mypage
    %li
      = render "templates/list", code:101 ,name:"マイページ"
    %li
      = render "templates/list", code:102 ,name:"お知らせ"
    %li
      = render "templates/list", code:103 ,name:"やることリスト"
    %li
      = render "templates/list", code:104 ,name:"いいね！一覧"
    %li
      = link_to "#", class:"user-menu__main__list__mypage--link" do
        出品する      
        .user-menu__main__list__mypage__arrow
          ＞
    %li
      = render "templates/list", code:106 ,name:"下書き一覧"
    %li
      = link_to user_products_path(current_user), class:"user-menu__main__list__mypage--link" do
        出品した商品-出品中
        .user-menu__main__list__mypage__arrow
          ＞
    %li
      = render "templates/list", code:108 ,name:"出品した商品-取引中"
    %li
      = render "templates/list", code:109 ,name:"出品した商品-売却済み"
    %li
      = render "templates/list", code:110 ,name:"購入した商品-取引中"
    %li
      = render "templates/list", code:111 ,name:"購入した商品-過去の取引"
    %li
      = render "templates/list", code:112 ,name:"ニュース一覧"
    %li
      = render "templates/list", code:113 ,name:"評価一覧"
    %li
      = render "templates/list", code:114 ,name:"ガイド"
    %li
      = render "templates/list", code:115 ,name:"お問い合わせ"

  %ul.user-menu__main__list__furipay
    フリペイ
    %li
      = render "templates/list", code:201 ,name:"売り上げ・振込申請"
    %li
      = render "templates/list", code:202 ,name:"ポイント"

  %ul.user-menu__main__list__setting
    設定
    %li
      = link_to edit_user_path(current_user), class:"user-menu__main__list__mypage--link" do
        = "プロフィール"       
        .user-menu__main__list__mypage__arrow
          ＞
    %li
      = link_to new_user_address_path(current_user), class:"user-menu__main__list__mypage--link" do
        = "発送元・お届け先住所変更"       
        .user-menu__main__list__mypage__arrow
          ＞
    %li
      = link_to "/card", class:"user-menu__main__list__mypage--link" do
        = "支払い方法"       
        .user-menu__main__list__mypage__arrow
          ＞
    %li
      = render "templates/list", code:304 ,name:"メール/パスワード"
    %li
      = render "templates/list", code:305 ,name:"本人情報"
    %li
      = render "templates/list", code:306 ,name:"電話番号の確認"
    %li
      = link_to destroy_user_session_path, method: :delete, class:"user-menu__main__list__mypage--link" do
        = "ログアウト"       
        .user-menu__main__list__mypage__arrow
          ＞