config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'toppage#index'

  resources :user_menu, only: [:show, :create]

  resources :products, except: :show

  resources :products, only: :show do
    post "/card", to: "card#buy"
  end

  get "/products/show2/:id", to: "products#show2"

  resources :users, only: [:index, :show, :new, :edit, :update] do
    resources :addresses, only: [:new, :create, :update]
  end
  
  resources :card, only: [:new, :index, :create, :destroy]

  resources :users do
    get "/products", to: "products#user_index"
  end

  resources :exhibition, only: [:index] 
end

app/models/address.rb
class Address < ApplicationRecord
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :zip, presence: true, length: { is: 7 }
  validates :area_id, presence: true
  validates :user_id, presence: true
  validates :city, presence: true
  validates :number, presence: true

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :area

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base

  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/card.rb
class Card < ApplicationRecord
  validates :user_id, presence: true, uniqueness: true
  validates :customer_id, presence: true
  validates :card_id, presence: true

  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image,  presence: true

  belongs_to :product

end

app/models/postage.rb
class Postage < ActiveHash::Base
  self.data = [
    {id: 1, text: '送料込み(出品者負担)'},
    {id: 2, text: '着払い(購入者負担)'}
]
end

app/models/product.rb
class Product < ApplicationRecord
  

  has_many :pictures, dependent: :destroy
  belongs_to :category
  belongs_to :user
  
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :name,:text,  presence: true
  validates :price, numericality:{greater_than: 300, less_than: 10000000}, presence: true
  validates :category_id, :size_id, :status_id, :postage_id, :area_id, :shipping_date_id, :user_id, presence: true

  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :status
  belongs_to_active_hash :area
  belongs_to_active_hash :postage
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :status
end

app/models/shipping_date.rb
class ShippingDate < ActiveHash::Base
  self.data = [
    {id: 1, text: '1~2日で発送'},
    {id: 2, text: '2~3日で発送'},
    {id: 3, text: '4~7日で発送'}
]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, text: 'Sサイズ'},
    {id: 2, text: 'Mサイズ'},
    {id: 3, text: 'Lサイズ'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, text: '新品、未使用'},
    {id: 2, text: '未使用に近い'},
    {id: 3, text: '目立った傷や汚れなし'},
    {id: 4, text: 'やや傷や汚れあり'},
    {id: 5, text: '傷や汚れあり'},
    {id: 6, text: '全体的に状態が悪い'}
]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 7 }, confirmation: true, unless: :without_validate
  attr_accessor :without_validate
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角ひらがな、全角カタカナ、漢字" }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/, message: "全角カタカナのみで入力して下さい" }
  validates :dob, presence: true

  has_one :address
  has_many :products
  has_one :card
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  
  before_action :set_categories, only: [:index, :new]
  before_action :set_card, only: [:new, :index, :destroy, :buy]
  before_action :user_signed?
  #pCardのデータベースからデータを取り出す
  def new
    redirect_to card_index_path if @card
  end

  #payjpとCardのデータベース作成を実施
  def create
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    if params['payjptoken'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params['payjptoken'])
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        render "new"
      end
    end
  end

  def index #Cardのデータpayjpに送り情報を取り出します
    if @card
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
      @card_exp = card_expiration(@default_card_information)
    end
  end

  def destroy #PayjpとCardデータベースを削除します
    if @card
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "index"
  end
  def buy
    @product = Product.find(params[:product_id])
    if @product.purchase == true #もし購入済みなら
      redirect_to root_path
    elsif @card.blank? #カード情報が無い場合
      redirect_to action: "new"
    elsif current_user.address.blank? #届け先住所が無い場合
      redirect_to new_user_address_path(current_user)
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      Payjp::Charge.create(
      amount: @product.price,
      customer: @card.customer_id,
      currency: 'jpy'
      )
      @product.update(purchase: true)
    end
  end
  private
    def set_categories
      @categories = Category.where(ancestry: nil)
    end

    def set_card
      @card = Card.find_by(user_id: current_user.id)
    end

    def card_expiration(card_info) #カード情報の有効期限をビュー表示用に変化
      exp_month = card_info.exp_month.to_s
      exp_year = card_info.exp_year.to_s.slice(2,3)
      return exp_month + " / " + exp_year
    end
    
    def user_signed?
      if current_user.blank?
        redirect_to new_user_session_path
      end
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/exhibition_helper.rb
module ExhibitionHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/helpers/user_menu_helper.rb
module UserMenuHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card/buy.html.haml
.header
  = render partial: 'templates/logo-header'    
.body
  .content
    .content__title
      購入が完了しました！
    .content__message
      購入完了しました。出品者の発送通知をお待ちください。
    .content__home
      .content__home__btn
        =link_to "/", class: "content__home__btn__link" do
          ホームへ
.footer
  = render partial: 'templates/logo-footer'

app/views/card/index.html.haml
= render 'templates/search-header', categories: @categories

.user-menu
  .user-menu__level
    %span 
      = link_to 'フリマ', root_path 
    %span 
      ＞ 
    - case @code
    - when '101'
      %span マイページ
    - else 
      = link_to 'マイページ', user_menu_path(id: "101",  name: "マイページ")
      %span 
        = " ＞ 支払い方法"

  .user-menu__main

    -# ユーザーメニューのサイドバー
    = render 'templates/usermenu-sidebar'

    -# ユーザーメニューのコンテンツ部分
    .user-menu__main__contents
      .card-index__title 支払い方法
      - if @card
        .card-index__box
          %label.card-index__box__inf 登録クレジットカード情報
          %br
          .card-index__box__num= "**** **** **** " + @default_card_information.last4
          %br
          .card-index__box__date= @card_exp
          = form_tag card_path(@card.id), method: :delete, id: 'charge-form',  name: "inputForm" do
            %input{ type: "hidden", name: "card_id", value: "" }
            %button.delete-btn 削除する
      - else
        = link_to "カード情報を登録する", new_card_path, class: "card-index-registry-btn"
          

app/views/card/new.html.haml
= render 'templates/search-header', categories: @categories

.user-menu
  .user-menu__level
    %span 
      = link_to 'フリマ', root_path 
    %span 
      ＞ 
    - case @code
    - when '101'
      %span マイページ
    - else 
      = link_to 'マイページ', user_menu_path(id: "101",  name: "マイページ")
      %span 
        = " ＞ 支払い方法"

  .user-menu__main

    -# ユーザーメニューのサイドバー
    = render 'templates/usermenu-sidebar'

    -# ユーザーメニューのコンテンツ部分
    .user-menu__main__contents
      .card-new__title クレジットカード情報入力
      = form_tag(card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %label{class: "card-new__number"}
          .card-new__number__text カード番号
          .card-new__number__alert.card-alert 必須
        = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        %br
        %label{class: "card-new__period"}
          .card-new__period__text 有効期限
          .card-new__period__alert.card-alert 必須
        .card-new__time
          %select#exp_month{name: "exp_month", type: "text", class: "card-new__month"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月/
          %select#exp_year{name: "exp_year", type: "text", class: "card-new__year"}
            %option{value: ""} --
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
            %option{value: "2030"}30
          %span 年
        %br
        %label{class: "card-new__security"} 
          .card-new__security__text セキュリティコード
          .card-new__security__alert.card-alert 必須
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
        = submit_tag "追加する", id: "token_submit"

app/views/card/show.html.haml
= render 'templates/search-header', categories: @categories

.user-menu
  .user-menu__level
    %span 
      = link_to 'フリマ', root_path 
    %span 
      ＞ 
    - case @code
    - when '101'
      %span マイページ
    - else 
      = link_to 'マイページ', user_menu_path(id: "101",  name: "マイページ")
      %span 
        = " ＞ 支払い方法"

  .user-menu__main

    -# ユーザーメニューのサイドバー
    = render 'templates/usermenu-sidebar'

    -# ユーザーメニューのコンテンツ部分
    .user-menu__main__contents
      .card-show__title 支払い方法
      - if @card
        .card-show__box
          %label.card-show__box__inf 登録クレジットカード情報
          %br
          .card-show__box__num= "**** **** **** " + @default_card_information.last4
          %br
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          .card-show__box__date= exp_month + " / " + exp_year
          = form_tag("/card/card/#{@card.id}", method: :delete, id: 'charge-form',  name: "inputForm") do
            %input{ type: "hidden", name: "card_id", value: "" }
            %button.delete-btn 削除する
      - else
        = link_to "カード情報を登録する", new_card_path, class: "card-show-registry-btn"
          