config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'toppage#index'

  resources :user_menu, only: [:show, :create]

  resources :products, except: :show

  resources :products, only: :show do
    post "/card", to: "card#buy"
  end

  get "/products/show2/:id", to: "products#show2"

  resources :users, only: [:index, :show, :new, :edit, :update] do
    resources :addresses, only: [:new, :create, :update]
  end
  
  resources :card, only: [:new, :index, :create, :destroy]

  resources :users do
    get "/products", to: "products#user_index"
  end

  resources :exhibition, only: [:index] 
end

app/models/product.rb
class Product < ApplicationRecord
  

  has_many :pictures, dependent: :destroy
  belongs_to :category
  belongs_to :user
  
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :name,:text,  presence: true
  validates :price, numericality:{greater_than: 300, less_than: 10000000}, presence: true
  validates :category_id, :size_id, :status_id, :postage_id, :area_id, :shipping_date_id, :user_id, presence: true

  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :status
  belongs_to_active_hash :area
  belongs_to_active_hash :postage
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :status
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_categories, only: [:index, :show]
  before_action :set_product, only: :show2
  before_action :check_user_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :product_purchased, only: :update

  # 商品一覧画面の表示
  def index
    @categories = Category.where(ancestry: nil)   
    @products = Product.new
    @children = Category.new
    @level = nil

    # 特定のカテゴリのみ閲覧
    unless(params[:all_view] == 'true')
      @view_all = false
      @category = Category.find(params[:id])

      case @level = @category.depth
      # 親カテゴリーの場合    
      when 0
        @children = @category.children
        @products = Product.where(category_id: @category.indirects.ids)

      # 子カテゴリーの場合  
      when 1
        @children = @category.children
        @products = Product.where(category_id: @children.ids)
       
      # 孫カテゴリーの場合  
      when 2
        @products = Product.where(category_id: params[:id])
      else
        
      end

    # 全カテゴリーを閲覧
    else
      @view_all = true
    end
  end


  # 商品出品画面の表示
  def new
    @product = Product.new
    @product.pictures.new

    @categories = Category.where(ancestry: nil)

    @category1 = []
    @category2 = []
    @category3 = []

    # 親レコードを取得
    @categories.each do |root|
      @category1.push([root.name, root.id])
    end    
  end


  # 出品した商品の出品処理
  def create
    @product = Product.new(product_params)

    # 画像データがあるか
    if params[:product][:pictures_attributes] != nil
      if @product.save  
      else
        redirect_to action: :new
      end
    else
      redirect_to action: :new
    end

  end

  # 商品詳細画面の表示
  def show
    @product = Product.find(params[:id])
    @categories = Category.where(ancestry: nil)
    @category = Category.find(params[:category_id])
    @level = @category.depth

    # 同一カテゴリの商品を取得
    @products = Product.where(category_id: params[:category_id])
  end

  #購入確認画面の表示
  def show2
    if current_user.blank?
      redirect_to new_user_session_path
    elsif @product.user.id == current_user.id || @product.purchase == true #購入済みの場合または出品者と購入ユーザーが一致している場合
      redirect_to root_path
    else
      if @card = current_user.card #現在のユーザーがカードを登録しているなら
        Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @default_card_information = customer.cards.retrieve(@card.card_id)
        @expiration = card_expiration(@default_card_information)
      end
      if current_user.address.present? #現在のユーザーが届け先住所を登録しているなら
        @zipcode = zipcode(current_user)
        @user_address = user_address(current_user)
      end
    end
  end

  # 出品している商品の削除処理
  def destroy
    product = Product.find(params[:id])
    if product
      product.destroy
    end
    redirect_to user_menu_path(id: 101, name: 'マイページ')
  end

  def edit
    @product = Product.find(params[:id])
    @p_category = @product.category
    if current_user.blank?
      redirect_to new_user_session_path
    elsif @product.user.id != current_user.id || @product.purchase == true
      redirect_to root_path
    end
    @categories = Category.where(ancestry: nil)

    @category1 = []
    @category2 = []
    @category3 = []

    # 親レコードを取得
    @categories.each do |root|
      @category1.push([root.name, root.id])
    end
    
    if @p_category.depth == 2
      @p_category.parent.siblings.each do |child|
        @category2.push([child.name, child.id])
      end
      @p_category.siblings.each do |grandchild|
        @category3.push([grandchild.name, grandchild.id])
      end
    end
    if @p_category.depth == 1
      @p_category.siblings.each do |child|
        @category2.push([child.name, child.id])
      end
    end
    
    gon.product = @product
    gon.product_pictures = @product.pictures

    # @product.product_imagse.image_urlをバイナリーデータにしてビューで表示できるようにする
    require 'base64'
    require 'aws-sdk'

    gon.product_pictures_binary_datas = []
    if Rails.env.production?
      client = Aws::S3::Client.new(
                             region: 'ap-northeast-1',
                             access_key_id: Rails.application.credentials.aws[:aws_access_key_id],
                             secret_access_key: Rails.application.credentials.aws[:aws_secret_access_key],
                             )
      @product.pictures.each do |image|
        binary_data = client.get_object(bucket: 'f77b-furima-images', key: image.image.file.path).body.read
        gon.product_pictures_binary_datas << Base64.strict_encode64(binary_data)
      end
    else
      @product.pictures.each do |image|
        binary_data = File.read(image.image.file.file)
        gon.product_pictures_binary_datas << Base64.strict_encode64(binary_data)
      end
    end
  end

  def update
    # 登録済画像のidの配列を生成
    ids = @product.pictures.map{|image| image.id }
    # 登録済画像のうち、編集後もまだ残っている画像のidの配列を生成(文字列から数値に変換)
    exist_ids = registered_image_params[:ids].map(&:to_i)
    # 登録済画像が残っていない場合(配列に０が格納されている)、配列を空にする
    exist_ids.clear if exist_ids[0] == 0
    # 何かしらの画像があり、かつ画像以外の情報が更新成功した場合
    if (exist_ids.length != 0 || new_image_params[:pictures][0] != " ") && @product.update(update_product_params)
      # 登録済画像のうち削除ボタンをおした画像を削除
      unless ids.length == exist_ids.length
        # 削除する画像のidの配列を生成
        delete_ids = ids - exist_ids
        delete_ids.each do |id|
          @product  .pictures.find(id).destroy
        end
      end

      # 新規登録画像があればcreate
      unless new_image_params[:pictures][0] == " "
        new_image_params[:pictures].each do |image|
          @product.pictures.create(image: image, product_id: @product.id)
        end
      end
      respond_to do |format|
        format.json{ 
          @status = 0
          @id = current_user.id
        } 
      end

    # 画像がないか画像以外の情報が更新失敗した場合
    else
      respond_to do |format|
        format.json{ 
          @status = 1
          @id = @product.id
        } 
      end
    end
  end

  # ユーザーメニューの出品情報を表示
  def user_index
    @categories = Category.where(ancestry: nil)
    @products = Product.where(user_id: params[:user_id])
  end


  private 

  def get_categories
    @categories = Category.where(ancestry: nil)
  end

  def product_params  
    params.require(:product).permit(:name, :text, :price, :brand, :status, :category_id, :size_id, :status_id, :postage_id, :area_id, :shipping_date_id, pictures_attributes: [:image]).merge(user_id: current_user.id)
  end

  def zipcode(user) #郵便番号に-を入れ込む
    str = user.address.zip.to_s
    return str.insert(3, "-")
  end

  def user_address(user) #ユーザー届け先住所を連結
    return user.address.area.name + user.address.city + user.address.number + user.address.building
  end

  def card_expiration(card_info) #カード情報の有効期限をビュー表示用に変化
    exp_month = card_info.exp_month.to_s
    exp_year = card_info.exp_year.to_s.slice(2,3)
    return exp_month + " / " + exp_year
  end

  def set_product #商品情報を引っ張ってくる
    @product = Product.find(params[:id])
  end

  # ログインしているかをチェックする
  def check_user_login
    redirect_to new_user_session_path unless user_signed_in?
  end

  def update_product_params
    params.require(:product).permit(:name, :text, :price, :brand, :status, :category_id, :size_id, :status_id, :postage_id, :area_id, :shipping_date_id).merge(user_id: current_user.id)
  end

  def registered_image_params
    params.require(:registered_images_ids).permit({ids: []})
  end

  def new_image_params
    params.require(:new_images).permit({pictures: []})
  end

  def product_purchased
    @product = Product.find(params[:id])
    if @product.purchase == true
      redirect_to root_path
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/views/products/_category-list.html.haml
.category-list
  .category-list__name
    = "#{category.name}の商品一覧"
  .category-list__children
    - category.children.each do |child|
      .category-list__children__links
        = link_to products_path(id: child.id, all_view:'false'), class:"category-list__children__links--link" do
          = child.name

app/views/products/_product-level.html.haml
.product-level
  = link_to "FURIMA", root_path, class:"product-evel--top"
  %span 
    ＞ 
  %span
    = link_to 'カテゴリ一覧', products_path(all_view:'true')
  - unless(level == nil)
    - if(level == 0)
      %span
        ＞
        = link_to products_path(id: category.id, all_view:'false') do
          = category.name

    -if(level == 1)
      %span
        ＞
        = link_to products_path(id: category.parent.id, all_view:'false') do
          = category.parent.name
      %span
        ＞
        = link_to products_path(id: category.id, all_view:'false') do
          = category.name
    -if(level == 2)
      %span
        ＞
        = link_to products_path(id: category.parent.parent.id, all_view:'false') do
          = category.parent.parent.name
      %span
        ＞
        = link_to products_path(id: category.parent.id, all_view:'false') do
          = category.parent.name
      %span
        ＞
        = link_to products_path(id: category.id, all_view:'false') do
          = category.name

app/views/products/create.html.haml
.simple-header
  =render 'templates/logo-header'
.products-create-body
  .products-create-body__content
    .products-create-body__content__title
      出品が完了しました！
    .products-create-body__content__message
      あなたが出品した商品は「出品した商品一覧」からいつでも見ることが出来ます。
    .products-create-body__content__home
      .products-create-body__content__home__btn
        =link_to "/", class: "products-create-body__content__home__btn__link" do
          ホームへ
.simple-footer
  =render 'templates/logo-footer'

app/views/products/edit.html.haml
.simple-header
  =render 'templates/logo-header'
.products-new
  .products-new__contents
    -# ↓コントローラ作成後,createページに飛ぶように指定して下さい(createのview作成済み)
    =form_with model: @product, local: true, class: 'products-new__contents__form', id: "edit_form" do |f|
      .products-new__contents__form__image
        .products-new__contents__form__image__box
          %p.products-new__contents__form__image__box__text 出品画像
          %p.products-new__contents__form__image__box__alert 必須
        .products-new__contents__form__image__title 最大10枚までアップロードできます
        #edit_item.products-new__contents__form__image--field

          = f.fields_for :product_pictures, @product.pictures.first do |image|
            .item__img__dropzone.clearfix
              #preview
              -# １〜５枚目プレビュー表示
              .item__img__dropzone__input
                = image.label :image, for: "upload-image" do
                  .input-area
                    = image.file_field :image_url, id: "upload-image", class: "upload-image", 'data-image': 0

                  .item__img__dropzone__input__description
                    .item__img__dropzone__input__description__text
                      ドラッグアンドドロップ
                      %br
                      またはクリックしてファイルをアップロード

            .item__img__dropzone2.clearfix
              #preview2
              -# ６〜１０枚目プレビュー表示
              .item__img__dropzone2__input2
                = image.label :image, for: "upload-image" do
                  .input-area
                    = image.file_field :image_url, id: "upload-image", class: "upload-image", 'data-image': 0
                  .item__img__dropzone2__input2__description
                    .item__img__dropzone2__input2__description__text
                      ドラッグアンドドロップ
                      %br
                      またはクリックしてファイルをアップロード

      .products-new__contents__form__item
        .products-new__contents__form__item__box
          %p.products-new__contents__form__item__box__text 商品名
          %p.products-new__contents__form__item__box__alert 必須
        =f.text_field :name, placeholder: '40文字まで', class: 'products-new__contents__form__item__textinput insert'
        .products-new__contents__form__item__explanation
          %p.products-new__contents__form__item__explanation__text 商品の説明
          %p.products-new__contents__form__item__explanation__alert 必須
        =f.text_area :text, placeholder: "商品の説明（必須 1,000文字以内）\r\n（色、素材、重さ、定価、注意点など）\r\n\r\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: 'products-new__contents__form__item__textarea insert'
        %p.products-new__contents__form__item__count 0/1000
      .products-new__contents__form__detail
        %p.products-new__contents__form__detail__title 商品の詳細
        .products-new__contents__form__detail__category
          %p.products-new__contents__form__detail__category__text カテゴリー
          %p.products-new__contents__form__detail__category__alert 必須
        =f.select :category_id, @category1, { selected: @product.category.parent.parent.id }, { class: 'products-new__contents__form__detail__select category-select products-select' }
        =f.select(:category_id, @category2, { selected: @product.category.parent.id }, { class: 'products-new__contents__form__detail__select category-select hidden1 p-edit1' },)
        -if @p_category.depth == 2
          =f.select :category_id, @category3, { selected: @product.category.id }, { class: 'products-new__contents__form__detail__select category-select hidden2 p-edit2' }
          .products-new__contents__form__detail__size.hidden-size.edit-box
            %p.products-new__contents__form__detail__size__text サイズ
            %p.products-new__contents__form__detail__size__alert 必須
          =f.collection_select :size_id, Size.all, :id, :text, { prompt: "選択してください" }, { class: 'products-new__contents__form__detail__select category-select hidden3 p-edit3' }
        -else 
          =f.select :category_id, @category3, { selected: @product.category.id }, { class: 'products-new__contents__form__detail__select category-select hidden2' }
          .products-new__contents__form__detail__size.hidden-size
            %p.products-new__contents__form__detail__size__text サイズ
            %p.products-new__contents__form__detail__size__alert 必須
          =f.collection_select :size_id, Size.all, :id, :text, { prompt: "選択してください" }, { class: 'products-new__contents__form__detail__select category-select hidden3' }
        .products-new__contents__form__detail__brand
          %p.products-new__contents__form__detail__brand__text ブランド
          %p.products-new__contents__form__detail__brand--any 任意
        =f.text_field :brand, placeholder: '例）シャネル', class: 'products-new__contents__form__detail__textinput'
        .products-new__contents__form__detail__status
          %p.products-new__contents__form__detail__status__text 商品の状態
          %p.products-new__contents__form__detail__status__alert 必須
        = f.collection_select :status_id, Status.all, :id, :text, { prompt: "選択してください" }, { class: 'products-new__contents__form__detail__select category-select' }
      .products-new__contents__form__shipping
        %p.products-new__contents__form__shipping__title 配送について
        .products-new__contents__form__shipping__category
          %p.products-new__contents__form__shipping__category__text 配送料の負担
          %p.products-new__contents__form__shipping__category__alert 必須
        = f.collection_select :postage_id, Postage.all, :id, :text, { prompt: "選択してください" }, { class: 'products-new__contents__form__shipping__select category-select' }
        .products-new__contents__form__shipping__brand
          %p.products-new__contents__form__shipping__brand__text 発送元の地域
          %p.products-new__contents__form__shipping__brand__alert 必須
        = f.collection_select :area_id, Area.all, :id, :name, { prompt: "選択してください" }, { class: 'products-new__contents__form__shipping__select category-select' }
        .products-new__contents__form__shipping__status
          %p.products-new__contents__form__shipping__status__text 発送までの日数
          %p.products-new__contents__form__shipping__status__alert 必須
        = f.collection_select :shipping_date_id, ShippingDate.all, :id, :text, { prompt: "選択して下さい" }, { class: 'products-new__contents__form__shipping__select category-select' }
      .products-new__contents__form__price
        %p.products-new__contents__form__price__title 価格（￥300〜9,999,999）
        .products-new__contents__form__price__box
          .products-new__contents__form__price__box__left
            %p.products-new__contents__form__price__box__left__text 販売価格
            %p.products-new__contents__form__price__box__left__alert 必須
          .products-new__contents__form__price__box__right
            %span.products-new__contents__form__price__box__right__yen  ￥
            =f.number_field :price, placeholder: '0', class: 'products-new__contents__form__price__box__right__numinput', min: 300, max: 9999999
        .products-new__contents__form__price__fee
          %span.products-new__contents__form__price__fee__text 販売手数料（10％）
          .products-new__contents__form__price__fee__num ー
        .products-new__contents__form__price__profit
          %span.products-new__contents__form__price__profit__text 販売利益
          .products-new__contents__form__price__profit__num ー
      .products-new__contents__form__btn
        =f.submit '変更する', class: 'products-new__contents__form__btn__submit'
        -# ↓リンク先未指定
        =link_to 'もどる', root_path, class: 'products-new__contents__form__btn__back'
.simple-footer
  =render 'templates/logo-footer'

app/views/products/index.html.haml
= render 'templates/search-header', categories: @categories

= render 'product-level', level: @level, category: @category

.product-list

  -# 全体一覧
  - if @view_all
    - @categories.each do |category|
      .product-list__categories
        .product-list__categories__name
          = "#{category.name}の商品一覧"
        .product-list__categories__children
          - category.children.each do |child| 
            .product-list__categories__children__name
              = link_to products_path(id: child.id,all_view:'false'), class:"product-list__categories__children__name--link" do
                -# 子カテゴリー
                = child.name
            .product-list__categories__children__g-child
              - child.children.each do |g_child|    
                .product-list__categories__children__g-child__list
                  = link_to products_path(id: g_child.id, all_view:'false'), class:"product-list__categories__children__g-child__list--link" do
                    -# 孫カテゴリー
                    = g_child.name
        .product-list__categories__back-to-top
          = icon('fas','arrow-up')
          ページ最上部へ移動
  - else
    = render 'category-list', category: @category
    .product-list__products
      - @products.each_with_index do |product, n|
        .product-list__products__overview
          = render 'templates/product-overview', product: product

= render 'templates/download-footer'

app/views/products/show.html.haml
= render 'templates/search-header', categories: @categories
= render 'product-level', level: @level, category: @category
.detail
  = render 'templates/exhibition-btn'
  .detail__wrapper
    .detail__wrapper__product
      .detail__wrapper__product__name
        = @product.name
      .detail__wrapper__product__picts
        .detail__wrapper__product__picts__main
          = image_tag @product.pictures[0].image.url, size: "600x400"
        %ul.detail__wrapper__product__picts__subs
        - @product.pictures.each do |image|
          %li.detail__wrapper__product__picts__subs__li
            = image_tag image.image.url, size: "140x140", class:"detail__wrapper__product__picts__subs__li"
      .detail__wrapper__product__price
        = number_to_currency(@product.price)  
      (税込)送料込み
      .detail__wrapper__product__text
        = @product.text

      %table.detail__wrapper__product__info{border: "1"}
        %tr
          %th 出品者
          %td 
            = @product.user.nickname
        %tr
          %th カテゴリー
          %td 
            .detail__wrapper__product__info_category
              = @product.category.parent.parent.name
            .detail__wrapper__product__info_category
              = @product.category.parent.name
            .detail__wrapper__product__info_category
              = @product.category.name
              
        %tr
          %th ブランド
          %td
            = @product.brand
        %tr
          %th 商品のサイズ
          %td
            = @product.size.text
        %tr
          %th 商品の状態
          %td 
            = @product.status.text
        %tr
          %th 配送料の負担
          %td 
            = @product.postage.text
        %tr
          %th 発送元の地域
          %td 
            = @product.area.name
        %tr
          %th 発送の目安
          %td 
            = @product.shipping_date.text
      .detail__wrapper__product__links
        - if user_signed_in? && current_user.id == @product.user_id
          .detail__wrapper__product__links__edit
            = link_to "商品を編集する", edit_product_path(@product), class: "detail__wrapper__product__links__edit__btn"
          .detail__wrapper__product__links__delete
            = link_to "商品を削除する", product_path(@product), method: :delete, class: "detail__wrapper__product__links__delete__btn"
        - else
          - if @product.purchase == false
            .detail__wrapper__product__links__buy
              = link_to "購入画面に進む", "/products/show2/#{@product.id}", class: "detail__wrapper__product__links__buy__btn"
          - else
            .detail__wrapper__product__links__status
              .detail__wrapper__product__links__status__true
                購入済の商品です

      .detail__wrapper__product__under
        .detail__wrapper__product__under__favorite
          = icon('fas','star')
          お気に入り 0 
        = link_to "#",class:"detail__wrapper__product__under__bad-report" do
          = icon('fab','font-awesome-flag')
          不適切な商品の通報

    .detail__wrapper__comments
      = form_with url:'#', class:"detail__wrapper__comments__form"   do |form|
        = form.text_area :comment, class: 'detail__wrapper__comments__form__comment'
        .detail__wrapper__comments__form__text
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        .detail__wrapper__comments__form__submit
          %label
            = icon('fas','comment')
            コメントする
            = form.submit '%', class:"detail__wrapper__comments__form__submit--btn"
    .detail__wrapper__selecter
      .detail__wrapper__selecter__prev
        = link_to "< 前の商品", "#", class:"detail__wrapper__selecter__prev--link"
      .detail__wrapper__selecter__next
        = link_to "次の商品 >", "#", class:"detail__wrapper__selecter__next--link"

    .detail__wrapper__other-products
      .detail__wrapper__other-products__title
        = @product.category.name
        をもっと見る
      .detail__wrapper__other-products__list
        - @products.each_with_index do |product, n|  
          .detail__wrapper__other-products__list__overview    
            = render 'templates/product-overview', product: product      

= render 'templates/download-footer'

app/views/products/show2.html.haml
.header
  = render partial: 'templates/logo-header'
.contents
  .content
    .contet__title
      .content__title__name
        購入内容の確認
    .content__product
      .content__product__items
        .content__product__items__img
          = image_tag @product.pictures[0].image.url, size: "64x64"
        .content__product__items__name
          = @product.name
          %p
            = number_to_currency(@product.price)
            （税込）送料込み
    .content__price
      .content__price__show
        支払い金額
      .content__price__shipping-fee
        = number_to_currency(@product.price)
    .content__credit
      -if @card
        .content__credit__title
          支払い方法
          =link_to card_index_path, target: :_blank, class:"content__credit__title__edit" do
            変更する
        .content__credit__box  
          .content__credit__box__name
            クレジットカード
          .content__credit__box__number
            = "**** **** **** " + @default_card_information.last4
          .content__credit__box__day
            = @expiration
      -else
        .content__credit__title
          支払い方法
        .content__creadit__btn
          =link_to new_card_path, target: :_blank, class:"content__creadit__btn__link show2-btn" do
            支払い方法を登録する
    .content__address
      -if current_user.address
        .content__address__title
          配送先
          =link_to new_user_address_path(current_user), target: :_blank, class:"content__address__title__edit" do
            変更する  
        .content__address__box
          .content__address__box__zip
            = "〒#{@zipcode}"
          .content__address__box__number
            = @user_address
          .content__address__box__name
            = current_user.address.last_name + current_user.address.first_name
      -else
        .content__address__title
          配送先
        .content__address__btn
          =link_to new_user_address_path(current_user), target: :_blank, class:"content__address__btn__link show2-btn" do
            配送先を登録する
    .content__buy
      -if current_user.address && @card
        .content__buy__btn
          =link_to product_card_path(@product.id), method: :post, class:"content__buy__btn__submit" do
            購入する
      -else
        .content__buy__btn.refusing-box
          支払い方法または配送先の情報が
          %br
          足りません
.footer
  = render partial: 'templates/logo-footer'

app/views/products/user_index.html.haml
= render 'templates/search-header', categories: @categories

.user-menu
  .user-menu__level
    %span 
      = link_to 'フリマ', root_path 
    %span 
      ＞ 
    - case @code
    - when '101'
      %span マイページ
    - else 
      = link_to 'マイページ', user_menu_path(id: "101",  name: "マイページ")
      %span 
        = " ＞ #{@name}"

  .user-menu__main

    -# ユーザーメニューのサイドバー
    = render 'templates/usermenu-sidebar'

    -# ユーザーメニューのコンテンツ部分
    .user-menu__main__contents
      .user-products__title 出品中商品一覧
      = render partial: 'templates/user-products', collection: @products, as: "product"